# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: TFSBuild-3

steps:
   - task: PowerShell@2
     inputs:
       targetType: 'inline'
       script: |
         Write-Host $(passIDarrayDev)
         Write-Host "##vso[task.setvariable variable=ConsumerKey]$(ConsumerKey-dev)"
         Write-Host "##vso[task.setvariable variable=ConsumerSecret]$(ConsumerSecret-dev)"
         Write-Host "##vso[task.setvariable variable=Token]$(Token-dev)"
         Write-Host "##vso[task.setvariable variable=TokenSecret]$(TokenSecret-dev)"
         Write-Host "##vso[task.setvariable variable=targetMachine]$(targetMachine-dev)"
         Write-Host "##vso[task.setvariable variable=passIDarray]$(passIDarrayDev)"
        
    
   - task: PowerShell@2
     inputs:
          targetType: 'inline'
          script: 'Write-Host $(passIDarray)'
             
    