# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: TFSBuild-3

steps:
   - task: CmdLine@2
     inputs:
       script: |
         echo "##vso[task.setvariable variable=ConsumerKey]$consumerKey-dev"
             echo $(ConsumerKey)

    
              
    