# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: TFSBuild-3

steps:
   - task: CmdLine@2
     inputs:
       script: |
         echo ##vso[task.setvariable variable=ConsumerKey]$(ConsumerKey-dev) 
         echo "##vso[task.setvariable variable=ConsumerSecret]$(ConsumerSecret-dev) "
         echo "##vso[task.setvariable variable=Token]$(Token-dev) "
         echo "##vso[task.setvariable variable=TokenSecret]$(TokenSecret-dev) "
         echo "##vso[task.setvariable variable=targetMachine]$(targetMachine-dev) "
         echo "##vso[task.setvariable variable=passIDarray]$(passIDarray-dev) "
    
   - task: CmdLine@2
     inputs:
        script: |
          echo $(ConsumerKey)
          echo $(ConsumerSecret)
          echo $(Token)
          echo $(TokenSecret)
          echo $(targetMachine)
          echo $(passIDarray)
    
              
    